export const SIGNAL_QUOTES = [
  { text: "Most candidates apply to everything. You're learning to apply to the right things.", attribution: null },
  { text: "The job search is a numbers game until you have better information. Now you do.", attribution: null },
  { text: "Rejection isn't feedback. A low fit score is feedback. There's a difference.", attribution: null },
  { text: "The candidates who get hired aren't always the most qualified. They're the most prepared.", attribution: null },
  { text: "Applying blind is hoping. This is strategy.", attribution: null },
  { text: "Right now someone else is applying to the same job with no idea whether they're actually competitive. You do.", attribution: null },
  { text: "Most resumes say the same thing. Yours is about to say something specific.", attribution: null },
  { text: "The interview starts before the interview. It starts with knowing why you belong in the room.", attribution: null },
  { text: "Your competition is guessing. You're not.", attribution: null },
  { text: "Good analysis takes a moment. Bad analysis is instant.", attribution: null },
  { text: "We're reading every line of that job description so you don't have to guess.", attribution: null },
  { text: "This is the part where SIGNAL does the work.", attribution: null },
  { text: "Thirty seconds now saves three hours of applying to the wrong thing.", attribution: null },
  { text: "The average job search takes 5 months. Strategy shortens that.", attribution: null },
  { text: "A resume that works for every job works for no job.", attribution: null },
  { text: "The best time to know your fit score was before you applied. Second best time is right now.", attribution: null },
  { text: "Most people find out they weren't a fit after the rejection. You're finding out now.", attribution: null },
  { text: "Every analysis makes the next decision easier.", attribution: null },
  { text: "You don't need more applications. You need better ones.", attribution: null },
  { text: "One well-targeted application beats ten blind ones every time.", attribution: null },
  { text: "Clarity is an advantage. Most candidates never have it.", attribution: null },
  { text: "The job exists. The question is whether it's the right one for you.", attribution: null },
  { text: "Not every job deserves your time. This analysis helps you figure out which ones do.", attribution: null },
  { text: "You're doing the work most candidates skip entirely.", attribution: null },
  { text: "This is what separating yourself actually looks like.", attribution: null },
  { text: "The candidates who get hired are appropriately aggressive. They don't wait to be found.", attribution: "— Peri Ginsberg, Workforce Ready Now" },
  { text: "Don't try to be everything to everyone. Tell one story at a time and tell it well.", attribution: "— Peri Ginsberg, Workforce Ready Now" },
  { text: "Don't apologize for experience you haven't gained yet.", attribution: "— Peri Ginsberg, Workforce Ready Now" },
  { text: "Whether you think you can, or you think you can't — you're right.", attribution: "— Henry Ford" },
] as const;
